import type { SVGProps } from "react";

export const SixDotsSpinner = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg
      fill="hsl(228, 97%, 42%)"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <circle cx="12" cy="3" r="0">
        <animate
          id="spinner_318l"
          begin="0;spinner_cvkU.end-0.5s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="16.50" cy="4.21" r="0">
        <animate
          id="spinner_g5Gj"
          begin="spinner_318l.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="7.50" cy="4.21" r="0">
        <animate
          id="spinner_cvkU"
          begin="spinner_Uuk0.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="19.79" cy="7.50" r="0">
        <animate
          id="spinner_e8rM"
          begin="spinner_g5Gj.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="4.21" cy="7.50" r="0">
        <animate
          id="spinner_Uuk0"
          begin="spinner_z7ol.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="21.00" cy="12.00" r="0">
        <animate
          id="spinner_MooL"
          begin="spinner_e8rM.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="3.00" cy="12.00" r="0">
        <animate
          id="spinner_z7ol"
          begin="spinner_KEoo.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="19.79" cy="16.50" r="0">
        <animate
          id="spinner_btyV"
          begin="spinner_MooL.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="4.21" cy="16.50" r="0">
        <animate
          id="spinner_KEoo"
          begin="spinner_1IYD.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="16.50" cy="19.79" r="0">
        <animate
          id="spinner_1sIS"
          begin="spinner_btyV.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="7.50" cy="19.79" r="0">
        <animate
          id="spinner_1IYD"
          begin="spinner_NWhh.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
      <circle cx="12" cy="21" r="0">
        <animate
          id="spinner_NWhh"
          begin="spinner_1sIS.begin+0.1s"
          attributeName="r"
          calcMode="spline"
          dur="0.6s"
          values="0;2;0"
          keyTimes="0;.2;1"
          keySplines="0,1,0,1;.53,0,.61,.73"
          fill="freeze"
        />
      </circle>
    </svg>
  );
};

export const BlocksWaveSpinner = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg
      fill="hsl(228, 97%, 42%)"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <rect x="1" y="1" width="7.33" height="7.33">
        <animate
          id="spinner_oJFS"
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="1" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="1" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="1" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="1" y="15.66" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="15.66" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="15.66" width="7.33" height="7.33">
        <animate
          id="spinner_5T1J"
          begin="spinner_oJFS.begin+0.4s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
    </svg>
  );
};
